---
- hosts: all
  become: true
  pre_tasks:

  - name: Install Updates (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: ubuntu
  become: true
  roles:
    - keystone
    - glance
    - nova

#- hosts: centos
 # become: true
 # roles:
 #   - keystone
 #   - glance
 #   - nova
